server:
  port: 80

spring:
  application:
    name: nacos-consumer-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.128:8848


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: nacos-provider-server
