server:
  port: 8002

spring:
  application:
    name: provide-server

eureka:
  client:
    serviceUrl:
      #      单机
      defaultZone: http://localhost:7001/eureka/
      #      集群
  #      defaultZone: http://eruake7001.com:7001/eureka/,http://eruake7002.com:7002/eureka/
  instance:
    instance-id: provide-server-8002  #修改主机名称
    prefer-ip-address: true   #访问路径显示IP地址
