server:
  port: 8001

spring:
  application:
    name: provide-server-8001

eureka:
  client:
    serviceUrl:
      #      单机
      #      defaultZone: http://localhost:7001/eureka/
      #      集群
      defaultZone: http://eruake7001.com:7001/eureka/,http://eruake7002.com:7002/eureka/
