server:
  port: 9527


spring:
  application:
    name: gateway
  cloud:
    gateway:
      #动态路由配置
      discovery:
        locator:
          enabled: true                       #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: eurake_provide_routh            #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001         # 匹配后提供服务的路由地址
          uri: lb://provide-server              #动态路由配置
          predicates:
            - Path=/hystrix/**                #断言，路径相匹配的进行路由
            - After=2022-05-12T16:03:24.112+08:00[Asia/Shanghai] #在这个时间之后才能正常路由
        - id: eurake_provide_routh2           #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://provide-server              #动态路由配置
          predicates:
            - Path=/msg/**                    #断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: gateway-server
  client:
    serviceUrl:
      #      单机
      defaultZone: http://localhost:7001/eureka/



