server:
  port: 8005

spring:
  application:
    name: consul-provide-server
  cloud:
    consul:
      host: 192.168.152.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
