eureka:
  client:
    serviceUrl:
      #      单机
      defaultZone: http://localhost:7001/eureka/
#      集群
#      defaultZone: http://eruake7001.com:7001/eureka/,http://eruake7002.com:7002/eureka/

server:
  port: 80

spring:
  application:
    name: consumer-service-80
  zipkin: #链路监控
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于 0 到 1 之间，1 则表示全部采集
        probability: 1

# hystrix开启配置
feign:
  hystrix:
    enabled: true

#设置feign客户端超时时间(openFeign默认支持ribbon)
ribbon:
  #指的是建立连接的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  connectTimeout: 5000

logging:
  levei:
    # feign 目志以什么级别监控哪个接口
    com.example.demo.FeignService: debug


