server:
  port: 3344

spring:
  application:
    name: config-server      #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/myacme/springcloud-config.git   #GitHub上面的git仓库名字
          search-paths: #搜索目录
            - springcloud-config
      label: master      #读取分支
      request-connect-timeout: 50000
  #rabbitmq相关配置
  rabbitmq:
    host: 192.168.152.128
    port: 5672
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      #      单机
      defaultZone: http://localhost:7001/eureka/


