server:
  port: 9001

spring:
  application:
    name: nacos-provider-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.128:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
      datasource: #持久化到nacos
        ds1:
          nacos:
            server-addr: 192.168.152.128:8848
            dataId: nacos-provider-server
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: *