server:
  port: 9001

spring:
  application:
    name: nacos-provider-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.128:8848

management:
  endpoints:
    web:
      exposure:
        include: *